name: NuGet Pack & Google Drive Upload

on:
  push:
    branches: [ master ]

jobs:
  build-test-pack:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      # - name: Setup VSTest
      #   uses: darenm/Setup-VSTest@v1

      - name: Restore NuGet Packages
        run: nuget restore BOL.sln

      - name: Build Solution
        run: msbuild.exe BOL.sln /p:Platform="Any CPU" /p:Configuration="Release"

      # - name: Run Unit Tests
      #   run: |
      #     vstest.console.exe .\tests\BOL.Tests\bin\Release\BOL.Tests.dll
          
      - name: NuGet Pack BOL Project
        id: nuget_pack
        run: |
          nuget pack BOL.csproj -OutputDirectory ./nupkgs
                   
      - name: Notify Google Chat - Pack Success
        if: steps.nuget_pack.outcome == 'success'
        run: |
          $body = @{ text = "✅ NuGet Pack Success: BOL.nupkg created." } | ConvertTo-Json -Depth 10
          Invoke-RestMethod -Uri "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}" -Method Post -ContentType 'application/json' -Body $body

      - name: Notify Google Chat - Pack Failure
        if: steps.nuget_pack.outcome == 'failure'
        run: |
          $body = @{ text = "❌ BOL.nupkg Creation Failed!" } | ConvertTo-Json -Depth 10
          Invoke-RestMethod -Uri "${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}" -Method Post -ContentType 'application/json' -Body $body

      - name: Install Rclone
        run: |
          choco install rclone -y

      - name: Upload .nupkg to Google Drive
        if: steps.nuget_pack.outcome == 'success'
        env:
          RCLONE_CONFIG_GDRIVE_TYPE: drive
          RCLONE_CONFIG_GDRIVE_SCOPE: drive
          RCLONE_CONFIG_GDRIVE_SERVICE_ACCOUNT_FILE: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
        run: |
          rclone copy ./nupkgs GDRIVE:MyFolder --progress
