name: NuGet Pack & Upload to Google Drive

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-pack:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet Packages
      run: nuget restore

    - name: Get Current Version from Git Tags
      id: versioning
      run: |
        $latestTag = git describe --tags --abbrev=0
        if (-not $latestTag) { $latestTag = "1.0.0" }
        Write-Output "Latest tag: $latestTag"
        $versionParts = $latestTag -split '\.'
        $patch = [int]$versionParts[2] + 1
        $newVersion = "$($versionParts[0]).$($versionParts[1]).$patch"
        echo "##[set-output name=version;]$newVersion"
      shell: pwsh

    - name: Build Solution (.NET 4.8.1)
      run: msbuild BOL.sln /p:Configuration=Release

    - name: Pack NuGet Package
      run: nuget pack BOL.csproj -Version ${{ steps.versioning.outputs.version }} -OutputDirectory ./nupkgs

    - name: Upload NuGet Package Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NuGetPackage
        path: ./nupkgs/*.nupkg

