name: Local NuGet Pack (.NET 4.8.1)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-pack:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet Packages
      run: msbuild BOL.sln /t:Restore

    - name: Build Solution (.NET 4.8.1)
      run: msbuild BOL.sln /p:Configuration=Release /p:TargetFrameworkVersion=v4.8.1 /t:Rebuild

    - name: Pack NuGet Package (Local Output)
      run: |
        nuget pack BOL.csproj -OutputDirectory ./nupkgs
        echo "NuGet package(s) generated in ./nupkgs"

    - name: Upload NuGet Package as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: LocalNuGetPackage
        path: ./nupkgs/*.nupkg